[test]
preload = [
  "./test/setup/happy-dom.ts",
  "./test/setup/testing-library.ts",
]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "src/components/ui/**",
  "src/env.ts",
  "src/server/db/schema.ts",
  "src/server/db/index.ts",
  "test/setup/**",
  "test/helpers/**",
  "test/fixtures/**",
]
